- vstools/functions/utils.py
A minor thing I noticed while reading the file.
Technically, it looks like current insert_clip works at runtime for `AudioNode`s as well as `VideoNode`s, and this change breaks it. But the type hints already require `VideoNode`s.
> insert_clip: combine repeated clip splicing

- tests/test_kernels.py
- vskernels/kernels/zimg.py
resize2 supports all of `force`, `force_h`, and `force_w`, so they no longer need to be popped from the args.
> vskernels: support force params in zimg kernels

- vsdenoise/deblock.py
- Fixes https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise/issues/135
Default num streams is now clamped to 2 when `num_streams=None` following the only other iteration in [BaseWaifu2x](https://github.com/Jaded-Encoding-Thaumaturgy/vs-jetpack/blob/370d06d256fd2a4dbe0c6340bc395ee666c10042/vsscale/scale.py#L315-L316)
- Adds docstrings
> Update dpir function

- vstools/types/generic.py
- vstools/utils/vs_enums.py
- vstools/utils/vs_proxy.py
PresetFormat has been removed in Vapoursynth R63 and vs-jetpack explicitly supports VS R68 and above
> Remove support for deprecated PresetFormat

- .github/workflows/autotag.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/pypipublish.yml
- .github/workflows/test.yml
Note that this won't magically work, needs a `WEBHOOK_URL` variable in repository secrets over [here](https://github.com/Jaded-Encoding-Thaumaturgy/vs-jetpack/settings/secrets/actions).
> CI: Add explicit failure webhook message to all workflows

- mkdocs.yml
`dpir` is an alias to `_dpir.DENOISE`. Since `_dpir` is private, it wasn't getting documented, but that's hardly helpful for the users of `dpir`, so add it to exemption filters. This is basically the same situation as `_dre_edgemask`.
> docs: include `_dpir`

- vssource/indexers/DGIndex.py
The unix-style commandline interface in DGIndex has existed since 2009 and supports filenames with spaces in them.
> vssource: Use the unix-style commandline interface of DGIndex

- vstools/functions/render.py
This PR does the following:
- Add an example usage to the docstrings (also very minor other docstring improvements)
- Add support for an SPathLike input. This should allow users to just pass a path and have it write to that rather than require them to pass a BinaryIO.
> clip_async_render: Add example and support SPathLike input

- vstools/utils/vs_proxy.py
I discovered there was a significant memory leak occurring, and traced it back to the caches in `vs-tools`. The issue was that, because the `Node`s stored in the caches keep references to the core, the `finalize_core` hook meant to clear the caches was never being called, because the caches themselves were keeping references to the core alive and preventing `weakref.finalize` from running.
This change uses Vapoursynth's built-in `register_on_destroy` callback, which hooks into the `Environment` instead of the `Core`, and causes the destructors to run correctly and the caches to clear.
Minimal test script:
```python
import vapoursynth as vs
core = vs.core
import vstools
clip = core.bs.VideoSource(source="testfile.mkv")
matrix = vstools.Matrix.from_video(clip)
clip.set_output(0)
``` …
> Use Vapoursynth's `register_on_destroy` to avoid caches leaking memory

- scripts/gen_ref_pages.py
This used to cause infinite recursion, but apparently it is fine now. Maybe since `PelType` was removed and IIRC that was one of if not _the_ offending item?
> docs: include vsdenoise.prefilters

- vsaa/funcs.py
- vsscale/funcs.py
- vsscale/helpers.py
Title & additional fixes on based_aa:
- `None` as a default argument is a custom behavior when the parameter allows it.
- `False` disables the related feature.
- Supersampled resolution rounding has been updated and no longer follows mod2 rounding.
> Remove vsscale dependency on vsaa & based_aa updates

- vsaa/abstract.py
- vskernels/kernels/abstract.py
- vskernels/kernels/placebo.py
- vskernels/util.py
- vsscale/helpers.py
The current implementation of `vskernels` checks the inherited classes within the `__init_subclass__` method defined in `BaseScaler` when the classes are constructed.
However, this approach has several issues:
- The `abstract_kernels` list is hardcoded with default values in a separate location, leading to a cumbersome design where you have to wait for these abstract classes to load.
- Abstract classes are bypassed and can be instantiated by the user, even if they haven't specified a kernel radius.
- Declaring "abstract" classes in a `__abstract__` list at the top of the file is misleading and questionable. These classes aren't truly abstract since they can still be instantiated, and the kernel radius check is simply skipped.
My proposed solution:
- Add a metaclass to `BaseScaler` to …
> vskernels: Replace `__init_subclass__` by a metaclass and instantiation check

- vsmasktools/abstract.py
When writing a script, I use the 'Copy cropping command' button in vspreview, which outputs `.std.CropAbs(XX, XX, XX, XX)`. This PR changes the argument order of `BoundingBox` to simplify script writing for masking. 
Although this will break existing scripts, I believe it's a more logical approach than the current one.
Fixes #34
> BoundingBox: revert argument order & add individual w/h/offset params

- vsdehalo/denoise.py
- vskernels/kernels/abstract.py
- vsscale/rescale.py
Minor changes across the codebase. `supersample` makes more intuitive sense to me than `multi`, and this method is also called by a `supersampler` scaler in other places.
> Kernel: Rename `multi` method to `supersample`, deprecate `multi`

- mkdocs.yml
Crazy PR.
Allows you to import the inventory in other docs sites to reference types and functions and link back to this one.
> docs: Enable inventory generation

- vsdeinterlace/funcs.py
Due to a mistake in the operation order, fields whose average exactly matches the desired target color were getting their values added to $color (effectively multiplied by two in case of pure-color fields), resulting in very wrong output except for fades to/from black.
> FixInterlacedFades: fix pure-$targetcolor field handling bug

- vsdenoise/blockmatch.py
As stated on the Github page, it's still under development.
Draft for now until https://github.com/Jaded-Encoding-Thaumaturgy/vs-jetpack/pull/80 is merged as I don't want to fix annoying conflicts
> Remove `bmdegrain` from vsdenoise

- vsmasktools/abstract.py
- vsmasktools/utils.py
- vsscale/rescale.py
- Add `replace_in`, `replace_out` and `planes` parameters for better general use case.
- Fixes wrong dimensions on right and bottom side of the region.
- Fixes wrong crops values on subsampled formats.
> rewrite region_rel_mask & region_abs_mask

- pyproject.toml
v0.5.X backport of https://github.com/Jaded-Encoding-Thaumaturgy/vs-jetpack/pull/126
> [v0.5.X] build: strictly limit what's included in the sdist

- vsdeband/debanders.py
- vsdehalo/denoise.py
This is a partial revert of https://github.com/Jaded-Encoding-Thaumaturgy/vs-jetpack/commit/c2852753d716a6179e2ff63af5e10ec0ab79b31a
> Restore `limit_filter` default arguments

- tests/vstools/functions/test_file.py
- vstools/functions/file.py
Usually this function is used like so (see the `VideoPackets` or `Keyframes` classes):
```python
storage.get_file("test", ext=".txt")
```
But:
```python
SPath(".txt").suffix == ""
```
So the extension was not being applied. Not sure if this used to work on a previous Python version or what.
If we think I should handle the case where someone tries `ext="txt"` (no `.`), then I can add that.
> vstools: fix get_file() extension handling

- vsdenoise/mvtools/motion.py
- vsdenoise/mvtools/mvtools.py
- vsdenoise/mvtools/presets.py
- vsdenoise/regress.py
- vskernels/abstract/base.py
- vskernels/util.py
- vsmasktools/hardsub.py
- vsscale/rescale.py
- vssource/formats/dvd/title.py
- vstools/functions/funcs.py
- vstools/types/utils.py
`vs_object` doesn't use anything from ABC or ABCMeta and is probably just a convenience thing. However that makes inheritance annoying when we have to set custom metaclasses like [here](https://github.com/Jaded-Encoding-Thaumaturgy/vs-jetpack/blob/2df39850fdad361b09fc357108cfc5d2bbfd38c7/vsexprtools/error.py#L23).
> vs_object: remove ABC inheritance

- vsaa/deinterlacers.py
This restores the old opt behavior as it appears AVX2 is faster than AVX512 in all scenarios.
> EEDI3: Explicitly set opt

- vsrgtools/blur.py
Until it's implemented in [zsmooth](https://github.com/adworacz/zsmooth/issues/16).
I'm getting ~700 fps without scenechanges and ~670 fps with it. Tested on a 1080p clip of 5000 frames.
> median_blur: add support for scene changes
